version: '3.4'

services:
  catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


  frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80

    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ordering:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


